# Generated by Django 3.2.16 on 2023-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231211_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='newuser',
            name='account_type',
            field=models.CharField(choices=[('V', 'Vendor'), ('U', 'User'), ('', 'Type of account')], default='', max_length=40),
        ),
    ]
